name: Test Scripts via Shellcheck

on:
  push:
    branches: [ "main", "dev" ]
    paths:
      - 'crash_test/scripts/**'
  pull_request:
    branches: [ "main", "dev" ]
    paths:
      - 'crash_test/scripts/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Shellcheck
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install shellcheck -y
      - name: Run Shellcheck
        run: |
          shellcheck ./scripts/npm_dependencies.sh
          shellcheck ./scripts/python_dependencies.sh
